language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: IhmjbUnacHf1Q4D+gq3BgM8yfX9dxNfVsX4IlB1OmD2qB182carfxfQ4yD+BdT8VBBBiESXFniOmD3jvkSmR7rQg5q4bW2QyZwWSZNWCX/W/UOF+14vowhxizyaEDRkc0DFdwEqhLHjQjqdlhTH/Hqc0vLVRMt9k1beEez8fKY2t2RbYMO3frzRUFooldoxXuN1jJwhuCmOSsefrDrdA7X47NupBUdmdGUOp9iKJSRwfvxqBGy3jDsTX7d1ugQjFCE03d75RNC+lpkRM/XqnCisAu5Ced/+mC8GVTdzwJL/RnPCydTUK8xMmT/qKDwB924rdaFwbeI/ESEVFL9RnGGdK8/w0CegSPLWGea2pcvz5x2v0lnLTyv7LmhEQNz0FWubd0II7XvnTFoPWmRCgpIBOaifjJ86GYrCbmliT1rdvN+bffZ2FczlsuGbJKdNKrPLNo2WIOHzPYLL2Cx9hfYORPhtXuaCx16pxzr1FQWuuzHTDuC5/m6RFsNunU6BEg0ob7R3gFcW36rkpLw9qulq+/58EtWTOed03M5nOIvGn/oQ07791sfxDtCdXHCh+UC3JOn64ztpxLMhZN7wgD32A/I/OliIFoNt0STlxq3Vj0pntRUY2bkF4w6DZ0Paac8RY2Qrc/SJAe/WHHw59cnfqHTzenoPG6cX/3CoL2a4=
  app: shrouded-shelf-73200
  on:
    repo: Becca529/Idea-Board
