language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: LtPfsCplNbpc9IcfROcc+SJgZOCUe1G7LPgea0dw//tCJwDLwaq8mlEIEIWLEPqfPzGr8brpOvFqoA3TYivrVX0btEYue43vOTmwvg9ilaOPIm10BRc2qdFFzbIX2BeBJLpEAOnJheO2JQx0a/tC3H/BahoLsrDbpneQH26DvpHk3srB16rm2rqxdm9ykhZDtff4JGU2T57Iaop5/+huowYs0EPFwTVGhoQCFusPMHeyW9ZQytkmIFXtSUKC8eLoUbKl2MGAoxTtpI3Rm5h7UC9O5FiggDT+Rb8WDIldUd2D7AE8VpygcUdKyW1RGPo4MweIYpna7jc8Y/M7VJp7UiX0Okgy2i0yWgyLqHd4IOn6Ve2O7ULu3xgeeQWZXYzoNani+VuSzbGglL9/VG/D9g5OEJ/aMdOlCL8Y9iGlg0lxvZ9GjgaldEa17wRy1hCEPCNmcSu8Rr+q8LueDRy3xsk7dhQJ2WQbE2O594mN43z0fm/vJQemI2mFD7XWdRE9iu8Lb1Oin0NLKE62P7l7izkUB0IJSOiqj/kviyPWncdtkIddZlZ8M2t08DCB0G+by27itRbf8gmNIBL6QtLpo3jPivog1V+nbZHWftIPKv8xcBCXz40403KWtvihrZpZc9v+DexxsiI2rWQwrXqUEvbhHitAacptj+PaZAhhbwg=
  app: shrouded-shelf-73200
  on:
    repo: Becca529/Idea-Board
