language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: QqxSwF/dTt8tTKv9uK2gLdIorpCkjBNfRRPFP3b7d1JSsvfRg91JXHOPvCUCz0nvJBt5QOBnpSiTGmdCzTkKDEMzhxW+1DfdhagETcdGiNZ/jaxSevRoOCGPzUrdAOmvL1OC3eBt1YW3VfuRq/UhL6scYBH53f0YiHlvAGilGIQNkSFHv32prD6hyfXtfDqufPMJWk3ibnpSopGiLDP5zIEcDLIYd05wutZwbPre/OGUcYAO/q2nFVeKIFn60x+uZVVzNasdWwJg+gb8gx2h7BL+HD5nXOYUir8BO7+FrFsa2Fd/cZBEx/NVsp1YC8PD7HreNob3as+qorloigTMnHY+sqsPj+uWY8BjGaBRHeEACdJlzM/eO69mAjAzNNBl0qOgvmTkxSOoObFVHeXp+xVkqwF8Ktb1D8MHleKzWJUAngoJGgZ0jkyMgYECF0hha51jDggWW29S1AwLWmjXXmSPHFyDPe2PZR4m/Vz63FUFyUATfRdj7HtMu4zP74Kdt23WQMI4tsSVPIxV+/vgcGWNaxr18NnKTAAwxj6qlWYdJlDwDue1MhVBlTwVITzwhozvGcmiuosOjaIObP0+AGMvYj2hBAEylYBdzqUKkCwibud9fEEyKqujc+NDgR5zi/0A2Qfevn1PKbSwilvWbYNze3zt26gbmFCC0DcRwbs=
  app: shrouded-shelf-73200
  on:
    repo: Becca529/Idea-Board
